language: java
jdk:
- oraclejdk12
before_install:
  - chmod +x mvnw
  - chmod +x ci/travis_beforeDeploy.sh
script: env && ./mvnw package -B && "./ci/travis_beforeDeploy.sh"
before_deploy: "./ci/travis_beforeDeploy.sh"